language = "C++"
include_guard = "MILO_H"
namespace = "milo"

[parse.expand]
crates = ["milo"]

[export]
include = [
  "Callback",
  "MessageTypes",
  "Connections",
  "Methods",
  "States",
  "Errors",
  "Parser",
  "methods",
]
