[package]
name = "milo-parser-macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
indexmap = { version = "2.0.0", features = ["serde"] }
proc-macro2 = "1.0.63"
regex = "1.9.1"
quote = "1.0.28"
semver = "1.0.19"
serde_yaml = "0.9.25"
serde_json = "1.0.107"
syn = { version = "2.0.18", features = ["full", "extra-traits"] }
toml = "0.8.2"
