/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function flags(a: number): void;
export function __wbg_parser_free(a: number): void;
export function parser_new(): number;
export function parser_reset(a: number, b: number): void;
export function parser_clear(a: number): void;
export function parser_pause(a: number): void;
export function parser_resume(a: number): void;
export function parser_finish(a: number): void;
export function parser_clearOffsets(a: number): void;
export function parser_new_wasm(a: number, b: number, c: number): number;
export function parser_parse(a: number, b: number, c: number): void;
export function parser_get_state(a: number): number;
export function parser_get_position(a: number): number;
export function parser_get_parsed(a: number): number;
export function parser_get_paused(a: number): number;
export function parser_get_error_code(a: number): number;
export function parser_get_error_description(a: number): number;
export function parser_get_id(a: number): number;
export function parser_set_id(a: number, b: number): void;
export function parser_get_mode(a: number): number;
export function parser_set_mode(a: number, b: number): void;
export function parser_get_manage_unconsumed(a: number): number;
export function parser_set_manage_unconsumed(a: number, b: number): void;
export function parser_get_continue_without_data(a: number): number;
export function parser_get_message_type(a: number): number;
export function parser_get_is_connect(a: number): number;
export function parser_set_is_connect(a: number, b: number): void;
export function parser_get_method(a: number): number;
export function parser_get_status(a: number): number;
export function parser_get_version_major(a: number): number;
export function parser_get_version_minor(a: number): number;
export function parser_get_connection(a: number): number;
export function parser_get_has_content_length(a: number): number;
export function parser_get_has_chunked_transfer_encoding(a: number): number;
export function parser_get_has_upgrade(a: number): number;
export function parser_get_has_trailers(a: number): number;
export function parser_get_content_length(a: number): number;
export function parser_get_chunk_size(a: number): number;
export function parser_get_remaining_content_length(a: number): number;
export function parser_get_remaining_chunk_size(a: number): number;
export function parser_get_unconsumed_len(a: number): number;
export function parser_get_skip_body(a: number): number;
export function parser_set_skip_body(a: number, b: number): void;
export function parser_set_input(a: number, b: number): void;
export function parser_set_offsets(a: number, b: number): void;
export function parser_setBeforeStateChange(a: number, b: number, c: number): void;
export function parser_setAfterStateChange(a: number, b: number, c: number): void;
export function parser_setOnError(a: number, b: number, c: number): void;
export function parser_setOnFinish(a: number, b: number, c: number): void;
export function parser_setOnMessageStart(a: number, b: number, c: number): void;
export function parser_setOnMessageComplete(a: number, b: number, c: number): void;
export function parser_setOnRequest(a: number, b: number, c: number): void;
export function parser_setOnResponse(a: number, b: number, c: number): void;
export function parser_setOnReset(a: number, b: number, c: number): void;
export function parser_setOnMethod(a: number, b: number, c: number): void;
export function parser_setOnUrl(a: number, b: number, c: number): void;
export function parser_setOnProtocol(a: number, b: number, c: number): void;
export function parser_setOnVersion(a: number, b: number, c: number): void;
export function parser_setOnStatus(a: number, b: number, c: number): void;
export function parser_setOnReason(a: number, b: number, c: number): void;
export function parser_setOnHeaderName(a: number, b: number, c: number): void;
export function parser_setOnHeaderValue(a: number, b: number, c: number): void;
export function parser_setOnHeaders(a: number, b: number, c: number): void;
export function parser_setOnConnect(a: number, b: number, c: number): void;
export function parser_setOnUpgrade(a: number, b: number, c: number): void;
export function parser_setOnChunkLength(a: number, b: number, c: number): void;
export function parser_setOnChunkExtensionName(a: number, b: number, c: number): void;
export function parser_setOnChunkExtensionValue(a: number, b: number, c: number): void;
export function parser_setOnChunk(a: number, b: number, c: number): void;
export function parser_setOnBody(a: number, b: number, c: number): void;
export function parser_setOnData(a: number, b: number, c: number): void;
export function parser_setOnTrailerName(a: number, b: number, c: number): void;
export function parser_setOnTrailerValue(a: number, b: number, c: number): void;
export function parser_setOnTrailers(a: number, b: number, c: number): void;
export function __wbindgen_export_0(a: number, b: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_export_2(a: number): void;
