/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function flags(): number;
export function alloc(a: number): number;
export function free(a: number, b: number): void;
export function create(a: number, b: number): number;
export function destroy(a: number): void;
export function reset(a: number, b: number): void;
export function clear(a: number): void;
export function parse(a: number, b: number, c: number): number;
export function pause(a: number): void;
export function resume(a: number): void;
export function finish(a: number): void;
export function fail(a: number, b: number, c: number, d: number): void;
export function clearOffsets(a: number): void;
export function getStateString(a: number, b: number): void;
export function getErrorCodeString(a: number, b: number): void;
export function getErrorDescriptionString(a: number, b: number): void;
export function getState(a: number): number;
export function getPosition(a: number): number;
export function getErrorCode(a: number): number;
export function getErrorDescriptionLen(a: number): number;
export function getUnconsumedLen(a: number): number;
export function getId(a: number): number;
export function getMode(a: number): number;
export function getMessageType(a: number): number;
export function getMethod(a: number): number;
export function getStatus(a: number): number;
export function getVersionMajor(a: number): number;
export function getVersionMinor(a: number): number;
export function getConnection(a: number): number;
export function getParsed(a: number): number;
export function getContentLength(a: number): number;
export function getChunkSize(a: number): number;
export function getRemainingContentLength(a: number): number;
export function getRemainingChunkSize(a: number): number;
export function isPaused(a: number): number;
export function manageUnconsumed(a: number): number;
export function continueWithoutData(a: number): number;
export function isConnect(a: number): number;
export function hasContentLength(a: number): number;
export function hasChunkedTransferEncoding(a: number): number;
export function hasUpgrade(a: number): number;
export function hasTrailers(a: number): number;
export function skipBody(a: number): number;
export function getOffsets(a: number): number;
export function getUnconsumed(a: number): number;
export function getErrorDescription(a: number): number;
export function getOwner(a: number): number;
export function getCallbackError(a: number): number;
export function setId(a: number, b: number): void;
export function setMode(a: number, b: number): void;
export function setManageUnconsumed(a: number, b: number): void;
export function setSkipBody(a: number, b: number): void;
export function setIsConnect(a: number, b: number): void;
export function __wbindgen_export_0(a: number): void;
export function __wbindgen_export_1(a: number, b: number): number;
export function __wbindgen_export_2(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_export_3(a: number, b: number, c: number): void;
